# Lab Activity

In [ ]:
import numpy as np

# 1. Using Numpy create the following Matrices

$ a = \begin{bmatrix} 3 & -4 \\ 8 & 5\end{bmatrix}$

$ b = \begin{bmatrix} 7 & 8 & -1\\ 3 & 6 & 9\end{bmatrix}$

In [ ]:
import numpy as np

In [ ]:
 a = np.array([3,-4,8,5]).reshape(2,2)
 b = np.array([7,8,-1,3,6,9]).reshape(2,3)

In [ ]:
 a

array([[ 3, -4],
       [ 8,  5]])

In [ ]:
b

array([[ 7,  8, -1],
       [ 3,  6,  9]])

# 2. Using NumPy . arrange() create the following:


In [ ]:
a. array([2, 4, 6, 8, 10, 12, 14, 18])

b. array([4, 8, 12, 16, 20, 24, 28, 32])

In [ ]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.arange(4,36,4)

array([ 4,  8, 12, 16, 20, 24, 28, 32])

# 3. Using NumPy .ones() create the Matrix below via simple multiplication

 $  c = \begin{bmatrix} 5 & 5 & 5\\ 5 & 5 & 5  \end{bmatrix}$

In [ ]:
np.ones((2,3)) * 5

array([[5., 5., 5.],
       [5., 5., 5.]])

# 4. Using Numpy .linspace create the array bellow:

In [ ]:
a. array([0, 2.5, 5., 7.5, 10.])

b. array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(2,20,10)

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

# 5. Using Numpy .rand create 5 random numbers

In [ ]:
np.random.rand(5)

array([0.83932496, 0.33229547, 0.71549678, 0.21830505, 0.66440213])

# 6. Using NumPy .rand create a 3 x 3 Matrix of random numbers

In [ ]:
np.random.randn(3,3)

array([[-0.16379601,  0.5195404 , -0.92822136],
       [-0.95541487, -0.18983753,  0.80912146],
       [-0.67289486,  1.94527084,  0.12391729]])

# 7. Create the following NumPy array and then select the following submatrices:

$ d = \begin{bmatrix} 2 & 4 & 6 & 8 & 10 & 12 & 14 & 16 \\ 18 & 20 & 22 & 24 & 26 & 28 & 30 & 32 \\ 34 & 36 & 38 & 40 & 42 & 44 & 46 & 48 \\ 50 & 52 & 54 & 56 & 58 & 60 & 62 & 64\end{bmatrix}$

In [ ]:
d = [[2,4,6,8,10,12,14,16],[18,20,22,24,26,28,30,32],[34,36,38,40,42,44,46,48],[50,52,54,56,58,60,62,64]]
d

[[2, 4, 6, 8, 10, 12, 14, 16],
 [18, 20, 22, 24, 26, 28, 30, 32],
 [34, 36, 38, 40, 42, 44, 46, 48],
 [50, 52, 54, 56, 58, 60, 62, 64]]

In [ ]:
np.arange(2,66,2).reshape(4,8)

array([[ 2,  4,  6,  8, 10, 12, 14, 16],
       [18, 20, 22, 24, 26, 28, 30, 32],
       [34, 36, 38, 40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58, 60, 62, 64]])

From Number 7, select the following submatrices

$ subd1 = \begin{bmatrix} 8 & 10 & 12 & 14 & 16\\ 24 & 26 & 28 & 30 & 32\\ 40 & 42 & 44 & 46 & 48 \end{bmatrix} $

In [ ]:
subd1 = np.arange(2,66,2).reshape(4,8)
subd1

In [ ]:
subd1[0:3,3:]

array([[ 8, 10, 12, 14, 16],
       [24, 26, 28, 30, 32],
       [40, 42, 44, 46, 48]])

$ subd2 = \begin{bmatrix} 22 & 24 & 26\\ 38 & 40 & 42\end{bmatrix} $



In [ ]:
subd2 = np.arange(2,66,2).reshape(4,8)
subd2

In [ ]:
subd2[1:3,2:5]

array([[22, 24, 26],
       [38, 40, 42]])

$ subd3 = \begin{bmatrix} 8 \\ 24 \\ 40\end{bmatrix} $

In [ ]:
subd3 = np.arange(2,66,2).reshape(4,8)
subd3

In [ ]:
subd3[0:3,3]

array([ 8, 24, 40])

$ subd4 = \begin{bmatrix} 36 & 38 & 40 & 42\end{bmatrix} $

In [ ]:
subd4 = np.arange(2,66,2).reshape(4,8)
subd4

In [ ]:
subd4[2,1:5]

array([36, 38, 40, 42])

$ subd5 = \begin{bmatrix} 38 & 48 \\ 54 & 64 \end{bmatrix} $

In [ ]:
subd5 = np.arange(2,66,2).reshape(4,8)
subd5

In [ ]:
subd5[2:,[2,7]]

array([[38, 48],
       [54, 64]])

Matrix Operation

Add and Subtract the two  Matrices

$ e = \begin{bmatrix} 5 & -1\\ 3 & -4 \\ 8 & 5\end{bmatrix} $

$ f = \begin{bmatrix} 2 & 4\\ -4 & 8 \\ 3 & 5\end{bmatrix} $



In [ ]:
e = np.array([5,-1,3,-4,8,5]).reshape(3,2)
f = np.array([2,4,-4,8,3,5]).reshape(3,2)

In [ ]:
e

array([[ 5, -1],
       [ 3, -4],
       [ 8,  5]])

In [ ]:
f

array([[ 2,  4],
       [-4,  8],
       [ 3,  5]])

In [ ]:
np.add(e,f)

array([[ 7,  3],
       [-1,  4],
       [11, 10]])

In [ ]:
np.subtract(e,f)

array([[  3,  -5],
       [  7, -12],
       [  5,   0]])

Multiply the matrix to scalar value

$ e = 4 \begin{bmatrix} 2 & 4 & 6\\ 1 & 2 & 3 \\ 5 & 4 & 3\end{bmatrix} $

In [ ]:
e = np.array([2,4,6,1,2,3,5,4,4]).reshape(3,3)

In [ ]:
np.multiply(4,e)

array([[ 8, 16, 24],
       [ 4,  8, 12],
       [20, 16, 16]])

Multiply the following Matrices

$ e = \begin{bmatrix} 3 & -2 & 8\\ 5 & 3 & 2 \\ 4 & -2 & 4\end{bmatrix} $

$ f = \begin{bmatrix} 1 & 4 \\ 1 & 2 \\ -1 & 3\end{bmatrix} $

In [ ]:
e = np.array([3,-2,8,5,3,2,4,-2,4]).reshape(3,3)
f = np.array([1,4,1,2,-1,3]).reshape(3,2)

In [ ]:
np.dot(e,f)

array([[-7, 32],
       [ 6, 32],
       [-2, 24]])

Find the Transpose of the Matrix

$ g = \begin{bmatrix} 2 & 4\\ 2 & 2 \\ 4 & 5\end{bmatrix} $

In [ ]:
g = np.array([2,4,2,2,4,5]).reshape(3,2)

In [ ]:
np.transpose(g)

array([[2, 2, 4],
       [4, 2, 5]])

Find the determinant of the Matrix

$ h = \begin{bmatrix} 1 & -3 & 4\\ 1 & -4 & 1 \\ -2 & -3 & 5\end{bmatrix} $

In [ ]:
h = np.array([1,-3,4,1,-4,1,-2,-3,5]).reshape(3,3)

In [ ]:
np.linalg.det(h)

-40.000000000000014

Find the Inverse of the Matrix

$ i = \begin{bmatrix} 7 & 2 & 1\\ 0 & 3 & -1 \\ -3 & 4 & -2\end{bmatrix} $

In [ ]:
i = np.array([7,2,1,0,3,-1,-3,4,-2]).reshape(3,3)

In [ ]:
np.linalg.inv(i)

array([[ -2.,   8.,  -5.],
       [  3., -11.,   7.],
       [  9., -34.,  21.]])

Solve the value 0f x: $ e^{2x} = 32 $

In [ ]:
x = np.log(32)/2

In [ ]:
x

1.7328679513998633