In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#Extract the specific element(For Numbers 1 to 3)

list_01 = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [ ]:
list_01[3:5]

[8, 10]

In [ ]:
list_01[4:8]

[10, 12, 14, 16]

In [ ]:
list_01[4:9]

[10, 12, 14, 16, 18]

In [ ]:
list_02 = [[1,2,3,[4,5,6,['a','b','c',['target'],7,8,9],10,11,12]]]
list_02[0][3][3][3]

['target']

In [ ]:
list_03 = [[1,2,3,[4,5,['a','b','c',['d','e','f','g',['h',['target'],6,7]],8,9]]]]
list_03[0][3][2][3][4][1]

['target']

In [ ]:
#6
list_04 = [[1,2,3,[4,[5,6,7,[8,9,10,[11,12,13,14,[15,['target']]]],16,17]],18]]
list_04[0][3][1][3][3][4][1]

['target']

In [ ]:
#7
d1 = {'k1':[1,2,3,{'Hello':['oh', 'man', 'this',{'is':[[1,2,3,['tricky']]]}]}]}
d1['k1'][3]['Hello'][3]['is'][0][3]

['tricky']

In [ ]:
#8
d2 = [{'k1':[[1,2,3,]],'k2':{'k3':[[4,6,6,'tricky']]}}]
d2[0]['k2']['k3'][0][3]

'tricky'

In [ ]:
#9
data = np.linspace(0,15,10)
data

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        , 11.66666667, 13.33333333, 15.        ])

In [ ]:
#10
eye = np.eye(9)
eye


array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
#11
np.random.seed(1)
random_array = np.random.randint(0,51,25)
random_array

array([37, 43, 12,  8,  9, 11,  5, 15,  0, 16,  1, 12,  7, 45,  6, 25, 50,
       20, 37, 18, 20, 11, 42, 28, 29])

In [ ]:
#12
np.random.seed(1)
random_array = np.random.randint(0,51,25).reshape(5,5)
random_array

array([[37, 43, 12,  8,  9],
       [11,  5, 15,  0, 16],
       [ 1, 12,  7, 45,  6],
       [25, 50, 20, 37, 18],
       [20, 11, 42, 28, 29]])

In [ ]:
#13
random_array[2:,2:]

array([[ 7, 45,  6],
       [20, 37, 18],
       [42, 28, 29]])

In [ ]:
#14
random_array[3,4:]

array([18])

In [ ]:
#15
random_array[1:4,2:]

array([[15,  0, 16],
       [ 7, 45,  6],
       [20, 37, 18]])

In [ ]:
#16
random_array[2:,2:]

array([[ 7, 45,  6],
       [20, 37, 18],
       [42, 28, 29]])

In [ ]:
#17
a = np.array([8,-4,5,8,5,-1,3,1,2]).reshape(3,3)
a

array([[ 8, -4,  5],
       [ 8,  5, -1],
       [ 3,  1,  2]])

In [ ]:
#18
np.linalg.det(a)

128.99999999999997

In [ ]:
19#
e = np.array([5,-2,8,5,3,2,4,-2,4]).reshape(3,3)
f = np.array([4,4,1,2,-1,3]).reshape(3,2)

e

array([[ 5, -2,  8],
       [ 5,  3,  2],
       [ 4, -2,  4]])

In [ ]:
np.dot(e,f)

array([[10, 40],
       [21, 32],
       [10, 24]])

In [ ]:
#20
np.random.seed(1)
df = pd.DataFrame(np.random.rand(6,6),['A','B','C','D','E','F'],['C1','C2','C3','C4','C5','C6'])
df

C1        C2        C3        C4        C5        C6
A  0.417022  0.720324  0.000114  0.302333  0.146756  0.092339
B  0.186260  0.345561  0.396767  0.538817  0.419195  0.685220
C  0.204452  0.878117  0.027388  0.670468  0.417305  0.558690
D  0.140387  0.198101  0.800745  0.968262  0.313424  0.692323
E  0.876389  0.894607  0.085044  0.039055  0.169830  0.878143
F  0.098347  0.421108  0.957890  0.533165  0.691877  0.315516